import { OnInit, ElementRef } from '@angular/core';
import { AttachmentX, AttachmentY, PopoverComponent } from '../popover/index';
import { TourService } from './tour.service';
export declare const VCLTourStepTag: string;
export declare class TourComponent implements OnInit {
    tour: TourService;
    private static readonly Tag;
    private tag;
    debug: boolean;
    debugPopover: boolean;
    readonly popover: PopoverComponent;
    title: string;
    order: number;
    target: string | ElementRef | Element;
    targetX: AttachmentX;
    attachmentX: AttachmentX;
    offsetAttachmentX: number;
    targetY: AttachmentY;
    attachmentY: AttachmentY;
    offsetAttachmentY: number;
    visible: boolean;
    hasNext: boolean;
    hasPrevious: boolean;
    constructor(tour: TourService);
    ngOnInit(): void;
    show(): void;
    hide(): void;
    previous(): void;
    next(): void;
    exit(): void;
    private disableClick(element);
    private enableClick(element);
    private enableHighlight(element);
    private disableHighlight(element);
}
