import { OnInit, ElementRef } from '@angular/core';
import { AttachmentX, AttachmentY, PopoverComponent } from '@ng-vcl/ng-vcl';
import { HintService } from './hint.service';
export declare class TourComponent implements OnInit {
    hint: HintService;
    private static readonly Tag;
    private readonly tag;
    readonly debug: boolean;
    readonly debugPopover: boolean;
    readonly popover: PopoverComponent;
    readonly classes: string;
    title: string;
    order: number;
    target: string | ElementRef | Element;
    targetX: AttachmentX;
    attachmentX: AttachmentX;
    targetY: AttachmentY;
    attachmentY: AttachmentY;
    visible: boolean;
    hasNext: boolean;
    hasPrevious: boolean;
    constructor(hint: HintService);
    ngOnInit(): void;
    showStep(): void;
    hideStep(): void;
    exit(): void;
    next(): void;
    previous(): void;
    private disableClick(element);
    private enableClick(element);
    private enableHighlight(element);
    private disableHighlight(element);
}
