import { NotificationType } from './types';
import { NotificationBodyComponent } from './notification-body.component';
import { NotificationFooterComponent } from './notification-footer.component';
import { NotificationHeaderComponent } from './notification-header.component';
import { Observable } from 'rxjs';
export declare class NotificationComponent {
    nType: 'default' | 'info' | 'warning' | 'error' | 'success';
    icon: string;
    iconClass: string;
    iconImage: string;
    iconSide: 'left' | 'right';
    drawIcon: boolean;
    header: string;
    footer: string;
    button: string;
    showButton: boolean;
    verticalBody: boolean;
    styleClass: object | string | undefined;
    headerAlign: 'left' | 'center' | 'right';
    bodyAlign: 'left' | 'center' | 'right';
    footerAlign: 'left' | 'center' | 'right';
    textColor: string;
    backgroundColor: string;
    headerComponent: NotificationHeaderComponent | null;
    bodyComponent: NotificationBodyComponent | null;
    footerComponent: NotificationFooterComponent | null;
    private buttonClickEvent;
    readonly buttonClick: Observable<any>;
    readonly eType: NotificationType;
    readonly notificationStyleClass: object | string;
    readonly notificationStyles: object;
    readonly eIconClass: string;
    readonly iconType: string;
    readonly nested: boolean;
    readonly headerStyle: object;
    readonly bodyStyle: object;
    readonly footerStyle: object;
    readonly bodyIconStyle: object;
    onClick(): void;
}
